### ISSUE TITLE
`fastlane-env-reminder` false positives

### ISSUE THREAD

**Issue by janpio** [fastlane/github-actions#10]
List of issues that triggered the bot although env info was provided:

**Comment by janpio** [comment]
https://github.com/fastlane/fastlane/issues/15353#issuecomment-533834647

**Comment by mollyIV** [comment]
Hey @janpio, 

The GitHub Action is triggered when an issue is created. 

> fastlane/fastlane#15353 (comment)

The issue description ☝️has been edited - can we confirm that `fastlane env` info was provided at time of issue creation? If the issue was created and then edited (provided `fastlane env`), the comment about providing missing env would be totally ok 👌

**Comment by janpio** [comment]
Ahh, good point! I will make it a feature request to maybe hide or delete the comment if the issue was edited and the information was added.

**Comment by mollyIV** [comment]
@janpio I had a look at the last 5 issues created on `fastlane` repository:

![image](https://user-images.githubusercontent.com/10795657/65572794-78a2b500-df69-11e9-959f-5fb1cd043d5c.png)

No false positives 🎉 

Can we please close this issue? Thanks 🙇
